return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    highlight = {
      enable = true,
    },
    rainbow = {
      enable = true,
      extended_mode = true,
      max_file_lines = 1000,
    },
    indent = {
      enable = true,
    },
    ensure_installed = {
      "bash",
      "c",
      "cpp",
      "dockerfile",
      "go",
      "gomod",
      "gosum",
      "hcl",
      "helm",
      "json",
      "jsonc",
      "lua",
      "luadoc",
      "luap",
      "make",
      "nix",
      "python",
      "regex",
      "terraform",
      "vim",
      "vimdoc",
      "yaml",
    },
  },
}
