# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "usbhid"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-6b75d2b7-0738-4e88-bffe-71ee997cbc8d";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-6b75d2b7-0738-4e88-bffe-71ee997cbc8d".device = "/dev/disk/by-uuid/6b75d2b7-0738-4e88-bffe-71ee997cbc8d";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6397-7C0F";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
